---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sdc-environment
  namespace: onap-sdc
data:
  AUTO.json: |
    {
       "name": "{{ .Values.env.name }}",
       "description": "OpenSource-{{ .Values.env.name }}",
       "cookbook_versions": {
                "Deploy-SDandC": "= 1.0.0"
       },
       "json_class": "Chef::Environment",
       "chef_type": "environment",
    
       "default_attributes": {
            "disableHttp": false,
            "CS_VIP": "sdc-cs.{{ .Values.nsPrefix }}-sdc",
            "BE_VIP": "sdc-be.{{ .Values.nsPrefix }}-sdc",
            "ONBOARDING_BE_VIP": "sdc-onboard-be.{{ .Values.nsPrefix }}-sdc",
            "FE_VIP": "sdc-fe.{{ .Values.nsPrefix }}-sdc",
            "ES_VIP": "sdc-es.{{ .Values.nsPrefix }}-sdc",
            "KB_VIP": "sdc-es.{{ .Values.nsPrefix }}-sdc",
            "interfaces": {
                "application": "eth0",
                "private": "eth1"
            },
            "ECompP": {
            	"ecomp_rest_url": "http://portal.api.simpledemo.onap.org:8989/ONAPPORTAL/auxapi",
                "ueb_url_list": "dmaap.{{.Values.nsPrefix}}, dmaap.{{.Values.nsPrefix}}",
                "app_secret": "XftIATw9Jr3VzAcPqt3NnJOu",
                "app_key": "x9UfO7JsDn8BESVX",
                "inbox_name": "ECOMP-PORTAL-INBOX",
                "ecomp_redirect_url": "http://portal.api.simpledemo.onap.org:8989/ECOMPPORTAL/login.htm",
                "app_topic_name": "ECOMP-PORTAL-OUTBOX-SDC1",
                "decryption_key": "AGLDdG4D04BKm2IxIWEr8o=="
            },
            "UEB": {
                "PublicKey": "iPIxkpAMI8qTcQj8",
                "SecretKey": "Ehq3WyT4bkif4zwgEbvshGal",
                "fqdn": ["dmaap.onap-message-router", "dmaap.onap-message-router"]
            },
            "Nodes": {
                "CS": "sdc-cs",
                "BE": "sdc-be",
                "ONBOARDING_BE": "sdc-onboard-be",
                "FE": "sdc-fe",
                "ES": "sdc-es",
                "KB": "sdc-kb"
            },
            "Plugins": {
                "DCAE": {
                    "dcae_discovery_url": "10.0.2.15",
                    "dcae_source_url": "10.0.2.15"
                },
                "WORKFLOW": {
                    "workflow_discovery_url": "10.0.2.15",
                    "workflow_source_url": "10.0.2.15"
                }
            },
               "VnfRepo": {
                 "vnfRepoPort": "8702",
                 "vnfRepoHost": "192.168.50.5"
               }
        },
        "override_attributes": {
            "FE": {
                "http_port": "8181",
                "https_port": "9443"
            },
            "BE": {
                "http_port": "8080",
                "https_port": "8443"
            },
            "ONBOARDING_BE": {
                "http_port": "8081",
                "https_port": "8445"
            },
            "elasticsearch": {
                "cluster_name": "SDC-ES-",
                "ES_path_home": "/usr/share/elasticsearch",
                "ES_path_data": "/usr/share/elasticsearch/data",
                "num_of_replicas": "0",
                "num_of_shards": "1"
            },
    
            "cassandra": {
                "concurrent_reads": "32",
                "num_tokens": "256",
                "data_dir": "/var/lib/cassandra/data",
                "hinted_handoff_enabled": "true",
                "cassandra_user": "asdc_user",
                "cassandra_password": "Aa1234%^!",
                "concurrent_writes": "32",
                "cluster_name": "SDC-CS-",
                "datacenter_name": "SDC-CS-",
                "multithreaded_compaction": "false",
                "cache_dir": "/var/lib/cassandra/saved_caches",
                "log_file": "/var/lib/cassandra/log/system.log",
                "phi_convict_threshold": "8",
                "commitlog_dir": "/var/lib/cassandra/commitlog",
                "socket_read_timeout": "20000",
                "socket_connect_timeout": "20000",
                "janusgraph_connection_timeout": "10000"
            }
        }
    }
  
