---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sdc-environment
  namespace: onap-sdc
data:
  AUTO.json: |
    {
       "name": "{{ .Values.env.name }}",
       "description": "OpenSource-{{ .Values.env.name }}",
       "cookbook_versions": {
                "Deploy-SDandC": "= 1.0.0"
       },
       "json_class": "Chef::Environment",
       "chef_type": "environment",

       "default_attributes": {
            "CS_VIP": "{{ .Values.env.vip }}",
            "BE_VIP": "{{ .Values.env.vip }}",
            "FE_VIP": "{{ .Values.env.vip }}",
            "ES_VIP": "{{ .Values.env.vip }}",
            "interfaces": {
                "application": "eth0",
                "private": "eth0"
            },
            "ECompP": {
                "ecomp_rest_url": "http://portalapps.onap-portal:8989/ONAPPORTAL/auxapi",
                "ueb_url_list": "dmaap.onap-message-router,dmaap.onap-message-router",
                "app_secret": "XftIATw9Jr3VzAcPqt3NnJOu",
                "app_key": "x9UfO7JsDn8BESVX",
                "inbox_name": "ECOMP-PORTAL-INBOX",
                "ecomp_redirect_url": "http://portalapps.onap-portal:8989/ONAPPORTAL/login.htm",
                "app_topic_name": "ECOMP-PORTAL-OUTBOX-SDC1",
                "decryption_key": "AGLDdG4D04BKm2IxIWEr8o=="
            },
            "UEB": {
                "PublicKey": "iPIxkpAMI8qTcQj8",
                "SecretKey": "Ehq3WyT4bkif4zwgEbvshGal",
                "fqdn": ["dmaap.onap-message-router", "dmaap.onap-message-router"]
            },
            "Nodes": {
                "CS": "{{ .Values.env.nodeCS }}",
                "BE": "{{ .Values.env.nodeBE }}",
                "FE": "{{ .Values.env.nodeFE }}",
                "ES": "{{ .Values.env.nodeES }}"
            },
            "Designers": {
                "DCAE": {
                    "dcae_host": "yyy",
                    "dcae_port": "yyy",
                    "dcae_path": "yyy",
                    "dcae_protocol": "yyy"
                },
                "WORKFLOW": {
                    "workflow_host": "yyy",
                    "workflow_port": "yyy",
                    "workflow_path": "yyy",
                    "workflow_protocol": "yyy"
                }
            }
        },
        "override_attributes": {
            "FE": {
                "http_port": "8181",
                "https_port": "9443"
            },
            "BE": {
                "http_port": "8080",
                "https_port": "8443"
            },
            "elasticsearch": {
                "cluster_name": "SDC-ES-",
                "ES_path_home": "/usr/share/elasticsearch",
                "ES_path_data": "/usr/share/elasticsearch/data",
                "num_of_replicas": "0",
                "num_of_shards": "1"
            },

            "cassandra": {
                "concurrent_reads": "32",
                "num_tokens": "256",
                "data_dir": "/var/lib/cassandra/data",
                "hinted_handoff_enabled": "true",
                "cassandra_user": "asdc_user",
                "cassandra_password": "Aa1234%^!",
                "concurrent_writes": "32",
                "cluster_name": "SDC-CS-",
                "multithreaded_compaction": "false",
                "cache_dir": "/var/lib/cassandra/saved_caches",
                "log_file": "/var/lib/cassandra/log/system.log",
                "phi_convict_threshold": "8",
                "commitlog_dir": "/var/lib/cassandra/commitlog",
                "socket_read_timeout": "20000",
                "socket_connect_timeout": "20000",
                "titan_connection_timeout": "10000"
            }
        }
    }
