tosca_definitions_version: tosca_simple_yaml_1_0_0
node_types:
    org.openecomp.nodes.Configuration:
        derived_from: tosca.nodes.Root
        properties:
          type:
            type: string
            description: The type of the node, the configuration will be defined for it. Ex. SBC
            required: false
          role:
            type: string
            description: The role of the node, the configuration will be defined for it. Ex. Active, Standby
            required: false
          function:
            type: string
            description: The function of the node, the configuration will be defined for it. Ex. NAT Traversal
            required: false

