cassandraConfig:
    cassandraHosts: ['${CS_HOST}']
    reconnectTimeout : 30000
    socketReadTimeout: 20000
    socketConnectTimeout: 20000
    authenticate: true
    username: ${CS_USER}
    password: ${CS_PASSWORD}
    ssl: ${CS_SSL_ENABLED}
    truststorePath : ${CS_TRUST_PATH}
    truststorePassword : ${CS_TRUST_PASSWORD}