nsPrefix: onap
pullPolicy: IfNotPresent
nodePortPrefix: 302
image:
  readiness: oomk8s/readiness-check:1.0.0
  sdcKibana: nexus3.onap.org:10001/onap/sdc-kibana:1.2-STAGING-latest
  sdcFrontend: nexus3.onap.org:10001/onap/sdc-frontend:1.2-STAGING-latest
  sdcElasticsearch: nexus3.onap.org:10001/onap/sdc-elasticsearch:1.2-STAGING-latest
  sdcCassandra: nexus3.onap.org:10001/onap/sdc-cassandra:1.2-STAGING-latest
  sdcBackend: nexus3.onap.org:10001/onap/sdc-backend:1.2-STAGING-latest
  sdcElasticsearchInit: nexus3.onap.org:10001/onap/sdc-init-elasticsearch:1.2-STAGING-latest
  sdcCassandraInit: nexus3.onap.org:10001/onap/sdc-cassandra-init:1.2-STAGING-latest
  sdcBackendInit: nexus3.onap.org:10001/onap/sdc-backend-init:1.2-STAGING-latest
  sdcOnboardBackendInit: nexus3.onap.org:10001/onap/sdc-onboard-cassandra-init:1.2-STAGING-latest
  sdcOnboardBackend: nexus3.onap.org:10001/onap/sdc-onboard-backend:1.2-STAGING-latest
  filebeat: docker.elastic.co/beats/filebeat:5.5.0

env:
  name: AUTO

secrets:
    sdc_user: YXNkY191c2Vy
    sdc_password: QWExMjM0JV4h
    cs_password: b25hcDEyMyNAIQ==

certDir: /var/lib/jetty/cert