# ---------------------------------------
# Module: gzip
--module=gzip

### GZip Configuration

## Minimum content length for compression (in bytes)
jetty.gzip.minGzipSize=1024

## Included MIME types for compression
jetty.gzip.includedMethodList=GET,POST

## Comma-separated list of included MIME types
jetty.gzip.includedMimeTypes=application/json,text/html,text/plain,application/javascript,text/css
