# Frontend hostname for logging purposes. To be populated by DevOps - currently dummy
feFqdn: catalog-fe

# Catalog backend hostname
beHost: catalog-be

# Catalog backend HTTP port
beHttpPort: 8080

# Catalog backend HTTP context
beContext: /sdc2/rest/v1/catalog/upload/resources

# Catalog backend protocol
beProtocol: http

# Catalog backend SSL port
beSslPort: 8443

# Threadpool size for handling requests
threadpoolSize: 50

# Request processing timeout (seconds)
requestTimeout: 1200

# Catalog MS (the host-port values need to be changed once it is deployed)
catalogFacadeMs:
  protocol: http
  host: ${CATALOG_FACADE_HOST}
  port: ${CATALOG_FACADE_PORT}
  healthCheckUri: "/healthCheck"
  path: "/uicache"

# Determines the health check read timeout when invoking health check towards the LB (or BE whatever is configured):
healthCheckSocketTimeoutInMs: 10000
healthCheckIntervalInSeconds: 10

basicAuth:
  enabled: true
  userName: testName
  userPass: testPass

onboarding:
  hostFe: localhost
  protocolFe: http
  portFe: 8181
  healthCheckUriFe: "/onboarding/v1.0/healthcheck"
  hostBe: onboarding-be
  protocolBe: http
  portBe: 8081

identificationHeaderFields:
  -
    - &HTTP_IV_USER HTTP_IV_USER
    - &iv-user iv-user
  -
    - &USER_ID USER_ID
    - &user-id user-id
  -
    - &HTTP_CSP_ATTUID HTTP_CSP_ATTUID
    - &csp-attuid csp-attuid

optionalHeaderFields:
  -
    - &HTTP_CSP_FIRSTNAME HTTP_CSP_FIRSTNAME
    - &csp-firstname csp-firstname
  -
    - &HTTP_CSP_LASTNAME HTTP_CSP_LASTNAME
    - &csp-lastname csp-lastname
  -
    - &HTTP_IV_REMOTE_ADDRESS HTTP_IV_REMOTE_ADDRESS
    - &iv-remote-address iv-remote-address
  -
    - &HTTP_CSP_EMAIL HTTP_CSP_EMAIL
    - &csp-email csp-email

version: 1.0
released: 2012-11-30

# Access restriction
authCookie:
  cookieName: "AuthenticationCookie"
  path: /
  domain: ""
  securityKey: MlB1WHFpSHNVTWdJZU1PcQ==

# Connection parameters
connection:
  url: jdbc:mysql://localhost:3306/db
  poolSize: 17

# Protocols
protocols:
  - http
  - https

systemMonitoring:
  enabled: false
  isProxy: true
  probeIntervalInSeconds: 15

healthStatusExclude:
  - DE
  - DMAAP
  - DCAE
  - DMAAP_PRODUCER
  - PORTAL
  - CATALOG_FACADE_MS
  - External API

# Space-separated list of permitted ancestors
permittedAncestors:
