pluginsList:
  - pluginId: POLICY
    pluginDiscoveryUrl: http://192.168.86.21:9090/policy/
    pluginSourceUrl: http://192.168.86.21:9090/policy/
    pluginStateUrl: "policy"
    pluginDisplayOptions:
      tab:
        displayName: "POLICY"
        displayRoles: ["DESIGNER"]
  - pluginId: POLICY_LIST
    pluginDiscoveryUrl: http://192.168.86.21:8095/artifact
    pluginSourceUrl: http://192.168.86.21:8095/artifact
    pluginStateUrl: "policy_list"
    pluginDisplayOptions:
      context:
        displayName: "Apex policy"
        displayContext: ["SERVICE"]
        displayRoles: ["DESIGNER"]
  - pluginId: WORKFLOW
    pluginDiscoveryUrl: http://192.168.86.21:8184/workflows
    pluginSourceUrl: http://192.168.86.21:8184/workflows
    pluginStateUrl: "workflowDesigner"
    pluginDisplayOptions:
      tab:
        displayName: "WORKFLOW"
        displayRoles: ["DESIGNER", "TESTER"]
      context:
        displayName: "Workflow Designer"
        displayContext: ["VF"]
        displayRoles: ["DESIGNER", "TESTER"]

connectionTimeout: 1000
