catalogNotificationsConfig:
  # catalog backend protocol
  catalogBeProtocol: http
  catalogBeHttpPort: 8080
  catalogBeSslPort: 8443
  catalogBeFqdn: sdc-BE
  # do not remove the "" from catalog_notification_url. it is escaping % characters coming from AUTO.json
  catalogNotificationUrl: "%s://%s:%s/sdc2/rest/v1/catalog/notif/vsp/"

notifications:
  pollingIntervalMsec: 2000
  selectionSize: 100
  beHost: sdc-onboard-BE
  beHttpPort: 8081

cassandraConfig:
  cassandraHosts: [ sdc-cs ]
  cassandraPort: 9042
  localDataCenter: SDC-CS-integration-test
  reconnectTimeout: 30000
  socketReadTimeout: 40000
  socketConnectTimeout: 40000
  authenticate: true
  username: asdc_user
  password: Aa1234%^!
  ssl: false
  truststorePath: /app/jetty/etc/truststore
  truststorePassword: Aa123456

authCookie:
  securityKey: MlB1WHFpSHNVTWdJZU1PcQ==
  maxSessionTimeOut: 86400000
  sessionIdleTimeOut: 3600000
  cookieName: "AuthenticationCookie"
  path: /
  domain: ""
  isHttpOnly: true
  # redirect variable name from portal.properties file
  redirectURL: "redirect_url"
  excludedUrls: [ '/.*' ]
  onboardingExcludedUrls: [ '/.*' ]

basicAuth:
  enabled: true
  userName: testName
  userPass: testPass
  excludedUrls: "/v1.0/healthcheck"

zipValidation:
  ignoreManifest: false

externalCsarStore:
  storageType: NONE # NONE, MINIO
  endpoint:
    host: 127.0.0.1
    port: 9000
    secure: false
  credentials:
    accessKey: "login"
    secretKey: "password"
  foldersToStrip:
    - Files/images
  sizeLimit: 10000000
  thresholdEntries: 10000
  tempPath: "/home/onap/temp/"
  uploadPartSize: 200000000

#Space separated list of permitted ancestors
permittedAncestors: 

# Comma separated list of excluded URLs by the DataValidatorFilter
dataValidatorFilterExcludedUrls: "/healthCheck,/followed,/authorize"

