#{{ if not .Values.disableSdcSdcCs }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sdc-cs
  name: sdc-cs
  namespace: "{{ .Values.nsPrefix }}-sdc"
spec:
  selector:
    matchLabels:
      app: sdc-cs
  template:
    metadata:
      labels:
        app: sdc-cs
      name: sdc-cs
    spec:
      containers:
      - name: sdc-cs
        image: "{{ .Values.image.sdcCassandra }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        env:
        - name: ENVNAME
          value: "{{ .Values.env.name }}"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CS_PASSWORD
          valueFrom:
            secretKeyRef: {name: sdc-cs-secret, key: cs_password}
        - name: MAX_HEAP_SIZE
          value: 1536M
        - name: HEAP_NEWSIZE
          value: 512M
        volumeMounts:
        - mountPath: /var/lib/cassandra/
          name: sdc-sdc-cs-cs
        - mountPath: /root/chef-solo/environments/
          name: sdc-environments
        - mountPath: /etc/localtime
          name: sdc-localtime
          readOnly: true
        - mountPath: /var/lib/jetty/logs
          name: sdc-logs
        ports:
        - containerPort: 9042
        readinessProbe:
          exec:
            command:
            - "/var/lib/ready-probe.sh"
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: sdc-sdc-cs-cs
        persistentVolumeClaim:
          claimName: sdc-cs-db
      - name: sdc-environments
        configMap:
          name: sdc-environment
      - name: sdc-localtime
        hostPath:
          path:  /etc/localtime
      - name:  sdc-logs
        hostPath:
          path:  /dockerdata-nfs/{{ .Values.nsPrefix }}/sdc/logs
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
