---
apiVersion: v1
kind: Secret
metadata:
  name: sdc-cs-secret
  namespace: onap-sdc
type: Opaque
data:
    #application user
    sdc_user: "{{ .Values.secrets.sdc_user }}"
    sdc_password: "{{ .Values.secrets.sdc_password }}"
    #default user:
    cs_password: "{{ .Values.secrets.cs_password }}"
    
