---
apiVersion: v1
kind: Secret
metadata:
  name: sdc-cs-secret
  namespace: onap-sdc
type: Opaque
data:
    #application user
    sdc_user: YXNkY191c2Vy
    sdc_password: QWExMjM0JV4h
    #default user:
    cs_password: b25hcDEyMyNAIQ==
    
