uebServers:
        - 10.0.11.1
        - 10.0.11.1
uebPublicKey: iPIxkpAMI8qTcQj8
uebSecretKey: Ehq3WyT4bkif4zwgEbvshGal
distributionNotifTopicName: SDC-DISTR-NOTIF-TOPIC-INT
distributionStatusTopicName: SDC-DISTR-STATUS-TOPIC
kafkaBootStrapServers: kafka-bootstrap-int:9092
initRetryIntervalSec: 5
initMaxIntervalSec: 60
distribNotifServiceArtifactTypes:
  info:
      - MURANO-PKG
distribNotifResourceArtifactTypes:
  lifecycle:
      - HEAT
      - DG-XML
environments:
   - integration-test
distributionStatusTopic:
   pollingIntervalSec: 60
   fetchTimeSec: 15
   consumerGroup: sdc-integration-test
   consumerId: sdc-integration-test1
distributionNotificationTopic:
   minThreadPoolSize: 0
   maxThreadPoolSize: 10
   maxWaitingAfterSendingSeconds: 5
createTopic:
   partitionCount: 1
   replicationCount: 1
startDistributionEngine: true
#This is false by default, since ONAP Dmaap currently doesn't support https
useHttpsWithDmaap: false
opEnvRecoveryIntervalSec: 180
allowedTimeBeforeStaleSec: 300
aaiConfig:
   httpRequestConfig:
      serverRootUrl: https://localhost:8443
      resourceNamespaces:
         operationalEnvironments: /aai/v12/cloud-infrastructure/operational-environments
   httpClientConfig:
      timeouts:
         readTimeoutMs: 5000
         connectTimeoutMs: 1000
      clientCertificate:
         keyStore: /app/jetty/base/be/etc/non-prod.jks
         keyStorePassword: hmXYcznAljMSisdy8zgcag==
      headers:
         X-FromAppId: asdc
      numOfRetries: 3
msoConfig:
   httpRequestConfig:
      serverRootUrl: http://127.0.0.1:8080/onap/mso/infra/modelDistributions/v1
      resourceNamespaces:
         distributions: /distributions
   httpClientConfig:
       timeouts:
          readTimeoutMs: 2000
          connectTimeoutMs: 500
       basicAuthorization:
          userName: asdc
          password: OTLEp5lfVhYdyw5EAtTUBQ==
       numOfRetries: 3
currentArtifactInstallationTimeout: 120

