####################################
# Cassandra CQL Storage Backend
####################################
storage.backend=cql

# Cassandra contact point(s)
storage.hostname=sdc-cs
storage.cql.contact-points=sdc-cs

# Cassandra Port
storage.port=9042
storage.cql.port=9042

# Authentication
storage.username=asdc_user
storage.password=Aa1234%^!

# Keyspace
storage.cql.keyspace=sdctitan

# Timeout
storage.connection-timeout=20000

####################################
# Cassandra Cluster Configuration
####################################

# Local Datacenter MUST match system.local.data_center
storage.cql.local-datacenter=SDC-CS-integration-test

# Replication Strategy (since single-node: RF=1)
storage.cql.replication-strategy-class=NetworkTopologyStrategy
storage.cql.replication-strategy-options=SDC-CS-integration-test:1

# Correct consistency for Write + Read (ONE for single-node)
storage.cql.read-consistency-level=ONE
storage.cql.write-consistency-level=ONE

####################################
# SSL DISABLED (Docker ENV)
####################################
storage.cql.ssl.enabled=false
storage.cql.ssl.keystore.location=
storage.cql.ssl.keystore.password=
storage.cql.ssl.truststore.location=
storage.cql.ssl.truststore.password=

####################################
# Janus / Titan Cache
####################################
cache.db-cache = true
cache.db-cache-clean-wait = 20
cache.db-cache-time = 180000
cache.db-cache-size = 0.5
cache.tx-cache-size = 1000000

####################################
# Titan Graph Options
####################################
storage.lock.retries=5
graph.replace-instance-if-exists=true
graph.set-vertex-id=true
