pluginsList:
   - pluginId: DCAED
     pluginDiscoveryUrl: <%= @dcae_discovery_url %>
     pluginSourceUrl: <%= @dcae_source_url %>
     pluginStateUrl: "dcaed"
     pluginDisplayOptions:
        context:
            displayName: "Monitoring"
            displayContext: ["SERVICE"]
            displayRoles: ["DESIGNER"]
   - pluginId: DCAE-DS
     pluginDiscoveryUrl: <%= @dcae_dt_discovery_url %>
     pluginSourceUrl: <%= @dcae_dt_source_url %>
     pluginStateUrl: "dcae-ds"
     pluginDisplayOptions:
       tab:
           displayName: "DCAE-DS"
           displayRoles: ["DESIGNER"]
   - pluginId: WORKFLOW
     pluginDiscoveryUrl: <%= @workflow_discovery_url %>
     pluginSourceUrl: <%= @workflow_source_url %>
     pluginStateUrl: "workflowDesigner"
     pluginDisplayOptions:
        tab:
            displayName: "WORKFLOW"
            displayRoles: ["DESIGNER", "TESTER"]

connectionTimeout: 1000